# This is a basic workflow to help you get started with Actions

name: "GitHub Actions SMZDM Bot"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # Runs a set of commands using the runners shell
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Working
        env:
          COOKIES: ${{__ckguid=or96Wl5N7ychWIlc6swbuX2; __jsluid_s=a823a9df055745df1c6927609667ac96; device_id=307423436416627249142517276a3af8ef1d21e1d8db77293cdf163cc6; homepage_sug=c; r_sort_type=score; footer_floating_layer=0; ad_date=27; ad_json_feed=%7B%7D; _zdmA.vid=*; Hm_lvt_9b7ac3d38f30fe89ff0b8a0546904e58=1666835488; sess=BA-1FErcBzMfyy0eRHzN6GmujQac4Bzq8i7Zz21P87Z2exj0eD2QRWUvJ6XADgtUyZ0rH6%2FyJ5VK5%2F8MP8ortz8LYLZiwohZGbENfz0%2FBtEOlGmF1jHZ0eogICH; user=user%3A3957862222%7C3957862222; smzdm_id=3957862222; smzdm_user_view=160E263E85101091D2FB772F4C7759AA; smzdm_user_source=6BA9E5CFDD5D81D79F0F8316295CEFD5; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%223957862222%22%2C%22first_id%22%3A%221832220c115655-0a05aa9d4a393d-3e604809-1821369-1832220c1164ae%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E5%BC%95%E8%8D%90%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC%22%2C%22%24latest_referrer%22%3A%22https%3A%2F%2Fgithub.com%2FWJ-8%2Fsmzdm_bot%22%7D%2C%22%24device_id%22%3A%221832220c115655-0a05aa9d4a393d-3e604809-1821369-1832220c1164ae%22%7D; _zdmA.uid=ZDMA.ADgvNPgmW.1666835682.2419200; Hm_lpvt_9b7ac3d38f30fe89ff0b8a0546904e58=1666835682; bannerCounter=%5B%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A5%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%5D; _zdmA.time=1666835702911.0.https%3A%2F%2Fwww.smzdm.com%2F}}
          SERVERCHAN_SECRETKEY: ${{ secrets.SERVERCHAN_SECRETKEY }}
        run: python main.py #>SMZDM_Bot.log
